3. django/0901/01_django_model/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('detail/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

3. django/0901/01_django_model/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

3. django/0901/01_django_model/articles/views.py
from django.shortcuts import render, redirect
# 명시적 상대경로
from .models import Article


# Create your views here.
def index(request):
    # 작성한 모든 게시글을 출력
    # 1. 모든 게시글 조회
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    # new로 부터 title과 content를 받아서 저장
    title = request.POST.get('title')
    content = request.POST.get('content')
    
    # 1
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 2
    article = Article(title=title, content=content)
    # 데이터 유효성 검사 및 전처리
    
    article.save()

    # 3
    # Article.objects.create(title=title, content=content)

    return redirect('articles:index')


def detail(request):
    return render(request, 'articles/detail.html')


def delete(request):
    pass


def edit(request):
    pass


def update(request):
    pass

3. django/0901/01_django_model/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
{% endblock %}

3. django/0901/01_django_model/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
{% endblock %}

3. django/0901/01_django_model/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>EDIT</h1>
{% endblock %}

3. django/0901/01_django_model/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:new' %}">NEW</a>
  <br><br>
  {% for article in articles %}
    <h2>제목 : {{ article.title }}</h2>
    <h4>내용 : {{ article.content }}</h4>
  {% endfor %}
{% endblock %}

3. django/0901/01_django_model/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE: </label>
    <input type="text" id="title" name="title">
    <br>
    <label for="content">CONTENT: </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <br>
    <input type="submit">
  </form>
  <br>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}